#gt915 touchpanel driver


obj-$(CONFIG_TOUCHSCREEN_GT9XX_TB8704)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_TOUCHSCREEN_GT9XX_TB8704)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_TOUCHSCREEN_GT9XX_TB8704)	+= goodix_tool.o
#selftest tool
#obj-$(CONFIG_TOUCHSCREEN_GT9XX)	+= gt9xx_openshort.o
