obj-$(CONFIG_ST_LSM303AGR_IIO) += lsm303agr.o
obj-$(CONFIG_ST_LSM303AGR_I2C_IIO) += lsm303agr_i2c.o
obj-$(CONFIG_ST_LSM303AGR_SPI_IIO) += lsm303agr_spi.o

lsm303agr-y += lsm303agr_core.o lsm303agr_trigger.o lsm303agr_buffer.o lsm303agr_acc.o lsm303agr_mag.o
